version: '3.8'
services:
  bookmarker-db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
  bookmarker-api:
    build: bookmarker-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://bookmarker-db:5432/appdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    depends_on:
      - bookmarker-db
volumes:
  pgdata: {}